### ISSUE TITLE
Running on OS X with Java 1.8

### ISSUE THREAD

**Issue by oschrenk** [jbachorik/btrace#125] opened 2015-06-14 20:02 UTC
I have some troubles running btrace on OS X with Java 1.8.05.

Initially it has some trouble finding the correct libraries but I made some progress on [my branch](https://github.com/oschrenk/btrace) to overcome those classpath issues but now I'm stuck with a `NullPointerException` within btrace being unable to get its runtime.

```
git clone git@github.com:oschrenk/btrace.git
cd btrace
git checkout jdk-1.7-osx
./gradlew build
./gradlew buildDistributions
cd build/distributions/
unzip btrace-bin-1.4-SNAPSHOT.zip
cd bin
wget https://raw.githubusercontent.com/jbachorik/btrace/master/samples/JStack.java
# start a java process and get its pid
./btrace <pid> JStack.java

> objc[19962]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
current: null
java.lang.NullPointerException
        at com.sun.btrace.BTraceRuntime.stackTraceAll(BTraceRuntime.java:1344)
        at com.sun.btrace.BTraceUtils$Threads.jstackAll(BTraceUtils.java:3300)
        at com.sun.btrace.BTraceUtils$Threads.jstackAll(BTraceUtils.java:3285)
        at com.sun.btrace.samples.JStack.<clinit>(Unknown Source)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at com.sun.btrace.BTraceRuntime.defineClassImpl(BTraceRuntime.java:2289)
        at com.sun.btrace.BTraceRuntime.defineClass(BTraceRuntime.java:444)
        at com.sun.btrace.agent.Client.loadClass(Client.java:287)
        at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:59)
        at com.sun.btrace.agent.Main.startServer(Main.java:405)
        at com.sun.btrace.agent.Main.access$000(Main.java:65)
        at com.sun.btrace.agent.Main$3.run(Main.java:168)
```

`current: null` is from a `println` statement I added. Can you help?

**Comment by oschrenk** [comment] 2015-06-14 20:18
Not sure if it related to the core issue but it seems that

```
> objc[19962]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
```

is an ongoing bug in the JDK for OS X. See [stackoverflow thread here](http://stackoverflow.com/questions/20794751/class-javalaunchhelper-is-implemented-in-both-one-of-the-two-will-be-used-whic) and open [JDK-8022291](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8022291)

**Comment by jbachorik** [comment] 2015-06-15 18:15
Fortunately for you, this is not caused by JDK 8 + OS X.

It is a regression in CLINIT generation code - the fix is available in [verifier-error](https://github.com/jbachorik/btrace/tree/verifier-error) branch and will be integrated to master soon.

**Closed** 2015-06-15 18:35 UTC
Labels: regression
