### ISSUE TITLE
'java.lang.VerifyError: Bad type on operand stack' when using OnTimer

### ISSUE THREAD

**Issue by ymmihw** [jbachorik/btrace#126] opened 2015-06-15 06:36 UTC
OS:win7 32
Java:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode)

btrace
BTrace v.1.3.0.1 (20150527)

traced source
======
	public static void main(String[] args) throws Exception {
		Random random = new Random();
		while (true) {
			HelloWorld.add(random.nextInt(10));
			Thread.sleep(1000);
		}
	}

	public static void add(int num) {
		System.out.println(num);
	}
======
btrace source
======
import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.BTrace;
import com.sun.btrace.annotations.OnTimer;

@BTrace
public class Deadlock {
	@OnTimer(4000)
	public static void ontimer() {
		BTraceUtils.println("123");
	}
}
======
command line
btrace.bat 7544 xxx.java

log
======
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/whimmy/btrace/helloworld/Deadlock.ontimer()V @3: ifne
  Reason:
    Type 'com/sun/btrace/BTraceRuntime' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @3
    flags: { }
    locals: { }
    stack: { 'com/sun/btrace/BTraceRuntime' }
  Bytecode:
    0x0000000: b200 139a 0004 b112 27b1 b1            
  Exception Handler Table:
    bci [7, 10] => handler: 10
  Stackmap Table:
    same_frame(@7)
    same_locals_1_stack_item_frame(@10,Object[#11])

	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.sun.btrace.BTraceRuntime.defineClassImpl(BTraceRuntime.java:2284)
	at com.sun.btrace.BTraceRuntime.defineClass(BTraceRuntime.java:444)
	at com.sun.btrace.agent.Client.loadClass(Client.java:287)
	at com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:59)
	at com.sun.btrace.agent.Main.startServer(Main.java:405)
	at com.sun.btrace.agent.Main.access$000(Main.java:65)
	at com.sun.btrace.agent.Main$3.run(Main.java:168)
	at java.lang.Thread.run(Thread.java:745)
======

**Comment by jbachorik** [comment] 2015-06-15 18:13
Caused by inconsistent usage of ASM4/ASM5 APIs.
The fix has been pushed to [verifier-error](https://github.com/jbachorik/btrace/tree/verifier-error) branch.

**Closed** 2015-06-15 18:35 UTC
Labels: BTRACE, Core, regression
